# Banking as Service
version: '3.8'
services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - ./config/keycloak/baas-realm.json:/opt/keycloak/data/import/baas-realm.json
