# Banking as Service
version: '3.8'
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - ./config/keycloak/baas-realm.json:/opt/keycloak/data/import/baas-realm.json

  service-discovery:
    image: rajeswaran/baas-service-discovery:1.0-SNAPSHOT
    container_name: service-discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5

  user-service:
    image: rajeswaran/baas-user-service:1.0-SNAPSHOT
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      broker:
        condition: service_started
      keycloak:
        condition: service_started

  account-service:
    image: rajeswaran/baas-account-service:1.0-SNAPSHOT
    container_name: account-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      user-service:
        condition: service_started
      broker:
        condition: service_started

  transaction-service:
    image: rajeswaran/baas-transaction-service:1.0-SNAPSHOT
    container_name: transaction-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      account-service:
        condition: service_started
      broker:
        condition: service_started

  payment-service:
    image: rajeswaran/baas-payment-service:1.0-SNAPSHOT
    container_name: payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      account-service:
        condition: service_started
      broker:
        condition: service_started

  notification-service:
    image: rajeswaran/baas-notification-service:1.0-SNAPSHOT
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      broker:
        condition: service_started

  audit-service:
    image: rajeswaran/baas-audit-service:1.0-SNAPSHOT
    container_name: audit-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      broker:
        condition: service_started


  api-gateway:
    image: rajeswaran/baas-api-gateway:1.0-SNAPSHOT
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/baas
    depends_on:
      service-discovery:
        condition: service_healthy
      keycloak:
        condition: service_started
      user-service:
        condition: service_started
      account-service:
        condition: service_started
      transaction-service:
        condition: service_started
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
      audit-service:
        condition: service_started
