spring:
  application:
    name: saga-orchestrator
server:
  port: 8090

# Eureka client config (if using service discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

