spring:
  application:
    name: saga-orchestrator
  cloud:
    stream:
      default-binder: kafka
      bindings:
        sagaEvents-out-0:
          destination: saga-events
      kafka:
        binder:
          brokers: localhost:9092
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
