spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
    stream:
      default-binder: kafka
      bindings:
        auditEvent-out-0:
          destination: audit-events
          content-type: application/json
        notificationEvent-out-0:
          destination: notification-events
          content-type: application/json
        paymentInitiatedEvent-out-0:
          destination: payment-initiated
          content-type: application/json
        paymentProcessedEvent-out-0:
          destination: payment-processed
          content-type: application/json
        paymentFailedEvent-out-0:
          destination: payment-failed
          content-type: application/json
        accountBalanceUpdatedEvent-in-0:
          destination: account-balance-updated
          group: payment-service
          content-type: application/json
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/baas}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8083
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n"

